apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaatra
  labels:
    app: yaatra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yaatra
  template:
    metadata:
      labels:
        app: yaatra
    spec:
      containers:
        - name: yaatra
          image: maradabhargavnaidu/yaatra:1
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DATABASE_URL
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secrets"
              readOnly: true
          ports:
            - containerPort: 3000
      volumes:
       - name: secret-volume
         secret:
           secretName: db-secret
